@startuml
Client -> Server: demande robots
Client <-- Server: reponse
group echanges Client - server
    Client -> Server: requete Omron
    Server -> "robots Omron": requete Omron
    Server <-- "robots Omron": reponse requete
    Client <-- Server: reponse requete
else fin de l'echange
    Client -> Server: requete fin
    Client <-- Server: reponse fin
else timeout
    Client <-- Server: timeout
end
@enduml