@startuml

actor "Étudiant" as etudiant
participant "Instance" as instance



alt main disponible
    etudiant -> instance: Requête de déplacement
    instance -> etudiant: Confirmation de déplacement
else main indisponible
    etudiant -> instance: Requête de déplacement
    note right of instance: L'instance affiche qu'une requete\nde l'étudiant n'a pas pu être transmise\nau serveur car il n'a pas la main.
end


@enduml
