@startuml

title Figure 1: Système de contrôle de robots pour l'apprentissage à distance

actor "Étudiant" as etudiant
participant "Instance" as instance
participant "Serveur" as serveur
participant "Robot" as robot



instance -> serveur: Demande de main
alt main disponible
    serveur -> instance: Réponse de demande de main (main libre)

    etudiant -> instance: Requête de déplacement
    instance -> serveur: Requête de déplacement
    serveur -> robot: Requête de déplacement
    robot -> serveur: Confirmation de déplacement
    serveur -> instance: Confirmation de déplacement
    instance -> etudiant: Confirmation de déplacement
else main indisponible
    serveur -> instance: Réponse de demande de main (position dans la file d'attente)
    
    etudiant -> instance: Requête de déplacement
    note right of instance: L'instance affiche qu'une requete de l'étudiant n'a pas\n pu être transmise au serveur car il n'a pas la main.
end


@enduml
